version: '3.7'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_URI: mongodb://mongodb:27017/admin
    depends_on: 
      - mongodb
volumes:
  mongodb-data:
networks:
  default:
    name: mongo_network